const foreCastData = {
  "location": {
    "name": "Singapore",
    "region": "",
    "country": "Singapore",
    "lat": 1.29,
    "lon": 103.86,
    "tz_id": "Asia/Singapore",
    "localtime_epoch": 1697514490,
    "localtime": "2023-10-17 11:48",
    "url": "Singapore-Singapore"
  },
  "current": {
    "last_updated_epoch": 1697514300,
    "last_updated": "2023-10-17 11:45",
    "temp_c": 32.0,
    "temp_f": 89.6,
    "is_day": 1,
    "condition": {
      "text": "Partly cloudy",
      "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
      "code": 1003
    },
    "wind_mph": 9.4,
    "wind_kph": 15.1,
    "wind_degree": 170,
    "wind_dir": "S",
    "pressure_mb": 1012.0,
    "pressure_in": 29.88,
    "precip_mm": 0.0,
    "precip_in": 0.0,
    "humidity": 59,
    "cloud": 75,
    "feelslike_c": 40.1,
    "feelslike_f": 104.2,
    "vis_km": 10.0,
    "vis_miles": 6.0,
    "uv": 7.0,
    "gust_mph": 13.8,
    "gust_kph": 22.2
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2023-10-17",
        "date_epoch": 1697500800,
        "day": {
          "maxtemp_c": 30.4,
          "maxtemp_f": 86.6,
          "mintemp_c": 27.9,
          "mintemp_f": 82.3,
          "avgtemp_c": 29.0,
          "avgtemp_f": 84.2,
          "maxwind_mph": 12.3,
          "maxwind_kph": 19.8,
          "totalprecip_mm": 0.81,
          "totalprecip_in": 0.03,
          "totalsnow_cm": 0.0,
          "avgvis_km": 10.0,
          "avgvis_miles": 6.0,
          "avghumidity": 72.0,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 83,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Patchy rain possible",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
            "code": 1063
          },
          "uv": 6.0
        },
        "astro": {
          "sunrise": "06:47 AM",
          "sunset": "06:52 PM",
          "moonrise": "08:32 AM",
          "moonset": "08:52 PM",
          "moon_phase": "Waxing Crescent",
          "moon_illumination": "5",
          "is_moon_up": 0,
          "is_sun_up": 1
        },
        "hour": [
          {
            "time_epoch": 1697472000,
            "time": "2023-10-17 00:00",
            "temp_c": 28.4,
            "temp_f": 83.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 121,
            "wind_dir": "ESE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.85,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 77,
            "cloud": 13,
            "feelslike_c": 32.8,
            "feelslike_f": 91.0,
            "windchill_c": 28.4,
            "windchill_f": 83.1,
            "heatindex_c": 32.8,
            "heatindex_f": 91.0,
            "dewpoint_c": 24.0,
            "dewpoint_f": 75.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 14.0,
            "gust_kph": 22.6,
            "uv": 1.0
          },
          {
            "time_epoch": 1697475600,
            "time": "2023-10-17 01:00",
            "temp_c": 28.3,
            "temp_f": 83.0,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 8.9,
            "wind_kph": 14.4,
            "wind_degree": 122,
            "wind_dir": "ESE",
            "pressure_mb": 1010.0,
            "pressure_in": 29.83,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 76,
            "cloud": 15,
            "feelslike_c": 32.4,
            "feelslike_f": 90.3,
            "windchill_c": 28.3,
            "windchill_f": 83.0,
            "heatindex_c": 32.4,
            "heatindex_f": 90.3,
            "dewpoint_c": 23.7,
            "dewpoint_f": 74.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.1,
            "gust_kph": 21.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1697479200,
            "time": "2023-10-17 02:00",
            "temp_c": 28.2,
            "temp_f": 82.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 125,
            "wind_dir": "SE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.81,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 76,
            "cloud": 19,
            "feelslike_c": 32.1,
            "feelslike_f": 89.8,
            "windchill_c": 28.2,
            "windchill_f": 82.8,
            "heatindex_c": 32.1,
            "heatindex_f": 89.8,
            "dewpoint_c": 23.5,
            "dewpoint_f": 74.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 14.0,
            "gust_kph": 22.6,
            "uv": 1.0
          },
          {
            "time_epoch": 1697482800,
            "time": "2023-10-17 03:00",
            "temp_c": 28.1,
            "temp_f": 82.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 10.3,
            "wind_kph": 16.6,
            "wind_degree": 123,
            "wind_dir": "ESE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.79,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 75,
            "cloud": 22,
            "feelslike_c": 31.8,
            "feelslike_f": 89.2,
            "windchill_c": 28.1,
            "windchill_f": 82.5,
            "heatindex_c": 31.8,
            "heatindex_f": 89.2,
            "dewpoint_c": 23.3,
            "dewpoint_f": 74.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 15.0,
            "gust_kph": 24.1,
            "uv": 1.0
          },
          {
            "time_epoch": 1697486400,
            "time": "2023-10-17 04:00",
            "temp_c": 27.9,
            "temp_f": 82.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 11.0,
            "wind_kph": 17.6,
            "wind_degree": 124,
            "wind_dir": "SE",
            "pressure_mb": 1008.0,
            "pressure_in": 29.78,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 75,
            "cloud": 23,
            "feelslike_c": 31.5,
            "feelslike_f": 88.7,
            "windchill_c": 28.0,
            "windchill_f": 82.3,
            "heatindex_c": 31.5,
            "heatindex_f": 88.7,
            "dewpoint_c": 23.2,
            "dewpoint_f": 73.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 16.0,
            "gust_kph": 25.8,
            "uv": 1.0
          },
          {
            "time_epoch": 1697490000,
            "time": "2023-10-17 05:00",
            "temp_c": 28.0,
            "temp_f": 82.3,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 11.6,
            "wind_kph": 18.7,
            "wind_degree": 130,
            "wind_dir": "SE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.78,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 75,
            "cloud": 30,
            "feelslike_c": 31.5,
            "feelslike_f": 88.7,
            "windchill_c": 28.0,
            "windchill_f": 82.3,
            "heatindex_c": 31.5,
            "heatindex_f": 88.7,
            "dewpoint_c": 23.2,
            "dewpoint_f": 73.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 16.9,
            "gust_kph": 27.2,
            "uv": 1.0
          },
          {
            "time_epoch": 1697493600,
            "time": "2023-10-17 06:00",
            "temp_c": 27.9,
            "temp_f": 82.3,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 10.3,
            "wind_kph": 16.6,
            "wind_degree": 126,
            "wind_dir": "SE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.8,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 75,
            "cloud": 36,
            "feelslike_c": 31.5,
            "feelslike_f": 88.7,
            "windchill_c": 28.0,
            "windchill_f": 82.3,
            "heatindex_c": 31.5,
            "heatindex_f": 88.7,
            "dewpoint_c": 23.1,
            "dewpoint_f": 73.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 15.0,
            "gust_kph": 24.2,
            "uv": 1.0
          },
          {
            "time_epoch": 1697497200,
            "time": "2023-10-17 07:00",
            "temp_c": 28.0,
            "temp_f": 82.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 10.5,
            "wind_kph": 16.9,
            "wind_degree": 133,
            "wind_dir": "SE",
            "pressure_mb": 1010.0,
            "pressure_in": 29.81,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 76,
            "cloud": 20,
            "feelslike_c": 31.8,
            "feelslike_f": 89.2,
            "windchill_c": 28.0,
            "windchill_f": 82.4,
            "heatindex_c": 31.8,
            "heatindex_f": 89.2,
            "dewpoint_c": 23.4,
            "dewpoint_f": 74.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 15.2,
            "gust_kph": 24.4,
            "uv": 7.0
          },
          {
            "time_epoch": 1697500800,
            "time": "2023-10-17 08:00",
            "temp_c": 28.4,
            "temp_f": 83.0,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 10.1,
            "wind_kph": 16.2,
            "wind_degree": 138,
            "wind_dir": "SE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.84,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 77,
            "cloud": 30,
            "feelslike_c": 32.6,
            "feelslike_f": 90.6,
            "windchill_c": 28.4,
            "windchill_f": 83.0,
            "heatindex_c": 32.6,
            "heatindex_f": 90.6,
            "dewpoint_c": 23.9,
            "dewpoint_f": 74.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.9,
            "gust_kph": 22.3,
            "uv": 7.0
          },
          {
            "time_epoch": 1697504400,
            "time": "2023-10-17 09:00",
            "temp_c": 28.9,
            "temp_f": 83.9,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 11.0,
            "wind_kph": 17.6,
            "wind_degree": 140,
            "wind_dir": "SE",
            "pressure_mb": 1012.0,
            "pressure_in": 29.87,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 75,
            "cloud": 32,
            "feelslike_c": 33.4,
            "feelslike_f": 92.1,
            "windchill_c": 28.9,
            "windchill_f": 83.9,
            "heatindex_c": 33.4,
            "heatindex_f": 92.1,
            "dewpoint_c": 24.0,
            "dewpoint_f": 75.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 14.6,
            "gust_kph": 23.5,
            "uv": 7.0
          },
          {
            "time_epoch": 1697508000,
            "time": "2023-10-17 10:00",
            "temp_c": 29.4,
            "temp_f": 84.9,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 11.0,
            "wind_kph": 17.6,
            "wind_degree": 149,
            "wind_dir": "SSE",
            "pressure_mb": 1012.0,
            "pressure_in": 29.88,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 73,
            "cloud": 34,
            "feelslike_c": 34.1,
            "feelslike_f": 93.4,
            "windchill_c": 29.4,
            "windchill_f": 84.9,
            "heatindex_c": 34.1,
            "heatindex_f": 93.4,
            "dewpoint_c": 24.0,
            "dewpoint_f": 75.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 14.4,
            "gust_kph": 23.1,
            "uv": 7.0
          },
          {
            "time_epoch": 1697511600,
            "time": "2023-10-17 11:00",
            "temp_c": 32.0,
            "temp_f": 89.6,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 170,
            "wind_dir": "S",
            "pressure_mb": 1012.0,
            "pressure_in": 29.88,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 59,
            "cloud": 75,
            "feelslike_c": 34.6,
            "feelslike_f": 94.3,
            "windchill_c": 29.8,
            "windchill_f": 85.7,
            "heatindex_c": 34.6,
            "heatindex_f": 94.3,
            "dewpoint_c": 23.8,
            "dewpoint_f": 74.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.8,
            "gust_kph": 22.2,
            "uv": 7.0
          },
          {
            "time_epoch": 1697515200,
            "time": "2023-10-17 12:00",
            "temp_c": 29.9,
            "temp_f": 85.9,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 11.2,
            "wind_kph": 18.0,
            "wind_degree": 177,
            "wind_dir": "S",
            "pressure_mb": 1011.0,
            "pressure_in": 29.85,
            "precip_mm": 0.02,
            "precip_in": 0.0,
            "humidity": 69,
            "cloud": 71,
            "feelslike_c": 34.7,
            "feelslike_f": 94.5,
            "windchill_c": 29.9,
            "windchill_f": 85.9,
            "heatindex_c": 34.7,
            "heatindex_f": 94.5,
            "dewpoint_c": 23.7,
            "dewpoint_f": 74.7,
            "will_it_rain": 1,
            "chance_of_rain": 83,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 14.6,
            "gust_kph": 23.5,
            "uv": 6.0
          },
          {
            "time_epoch": 1697518800,
            "time": "2023-10-17 13:00",
            "temp_c": 29.9,
            "temp_f": 85.8,
            "is_day": 1,
            "condition": {
              "text": "Moderate rain at times",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/299.png",
              "code": 1186
            },
            "wind_mph": 11.9,
            "wind_kph": 19.1,
            "wind_degree": 177,
            "wind_dir": "S",
            "pressure_mb": 1010.0,
            "pressure_in": 29.83,
            "precip_mm": 0.62,
            "precip_in": 0.02,
            "humidity": 69,
            "cloud": 74,
            "feelslike_c": 34.4,
            "feelslike_f": 94.0,
            "windchill_c": 29.9,
            "windchill_f": 85.8,
            "heatindex_c": 34.4,
            "heatindex_f": 94.0,
            "dewpoint_c": 23.5,
            "dewpoint_f": 74.2,
            "will_it_rain": 0,
            "chance_of_rain": 70,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 15.7,
            "gust_kph": 25.3,
            "uv": 6.0
          },
          {
            "time_epoch": 1697522400,
            "time": "2023-10-17 14:00",
            "temp_c": 30.2,
            "temp_f": 86.4,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 12.1,
            "wind_kph": 19.4,
            "wind_degree": 176,
            "wind_dir": "S",
            "pressure_mb": 1009.0,
            "pressure_in": 29.8,
            "precip_mm": 0.16,
            "precip_in": 0.01,
            "humidity": 67,
            "cloud": 77,
            "feelslike_c": 34.9,
            "feelslike_f": 94.8,
            "windchill_c": 30.2,
            "windchill_f": 86.4,
            "heatindex_c": 34.9,
            "heatindex_f": 94.8,
            "dewpoint_c": 23.4,
            "dewpoint_f": 74.2,
            "will_it_rain": 1,
            "chance_of_rain": 71,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 15.8,
            "gust_kph": 25.4,
            "uv": 7.0
          },
          {
            "time_epoch": 1697526000,
            "time": "2023-10-17 15:00",
            "temp_c": 30.4,
            "temp_f": 86.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 12.3,
            "wind_kph": 19.8,
            "wind_degree": 167,
            "wind_dir": "SSE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.79,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 66,
            "cloud": 12,
            "feelslike_c": 34.9,
            "feelslike_f": 94.8,
            "windchill_c": 30.4,
            "windchill_f": 86.6,
            "heatindex_c": 34.9,
            "heatindex_f": 94.8,
            "dewpoint_c": 23.2,
            "dewpoint_f": 73.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 16.1,
            "gust_kph": 25.9,
            "uv": 8.0
          },
          {
            "time_epoch": 1697529600,
            "time": "2023-10-17 16:00",
            "temp_c": 30.3,
            "temp_f": 86.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 12.3,
            "wind_kph": 19.8,
            "wind_degree": 164,
            "wind_dir": "SSE",
            "pressure_mb": 1008.0,
            "pressure_in": 29.77,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 66,
            "cloud": 11,
            "feelslike_c": 34.8,
            "feelslike_f": 94.6,
            "windchill_c": 30.3,
            "windchill_f": 86.6,
            "heatindex_c": 34.8,
            "heatindex_f": 94.6,
            "dewpoint_c": 23.1,
            "dewpoint_f": 73.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 16.1,
            "gust_kph": 25.9,
            "uv": 8.0
          },
          {
            "time_epoch": 1697533200,
            "time": "2023-10-17 17:00",
            "temp_c": 30.0,
            "temp_f": 86.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 11.9,
            "wind_kph": 19.1,
            "wind_degree": 163,
            "wind_dir": "SSE",
            "pressure_mb": 1008.0,
            "pressure_in": 29.77,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 67,
            "cloud": 10,
            "feelslike_c": 34.5,
            "feelslike_f": 94.0,
            "windchill_c": 30.0,
            "windchill_f": 86.1,
            "heatindex_c": 34.5,
            "heatindex_f": 94.0,
            "dewpoint_c": 23.2,
            "dewpoint_f": 73.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 15.9,
            "gust_kph": 25.6,
            "uv": 8.0
          },
          {
            "time_epoch": 1697536800,
            "time": "2023-10-17 18:00",
            "temp_c": 29.5,
            "temp_f": 85.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 11.0,
            "wind_kph": 17.6,
            "wind_degree": 163,
            "wind_dir": "SSE",
            "pressure_mb": 1008.0,
            "pressure_in": 29.78,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 70,
            "cloud": 16,
            "feelslike_c": 34.0,
            "feelslike_f": 93.2,
            "windchill_c": 29.5,
            "windchill_f": 85.2,
            "heatindex_c": 34.0,
            "heatindex_f": 93.2,
            "dewpoint_c": 23.6,
            "dewpoint_f": 74.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 15.3,
            "gust_kph": 24.6,
            "uv": 7.0
          },
          {
            "time_epoch": 1697540400,
            "time": "2023-10-17 19:00",
            "temp_c": 29.2,
            "temp_f": 84.6,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 10.7,
            "wind_kph": 17.3,
            "wind_degree": 155,
            "wind_dir": "SSE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.79,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 72,
            "cloud": 14,
            "feelslike_c": 33.6,
            "feelslike_f": 92.4,
            "windchill_c": 29.2,
            "windchill_f": 84.6,
            "heatindex_c": 33.6,
            "heatindex_f": 92.4,
            "dewpoint_c": 23.6,
            "dewpoint_f": 74.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 15.2,
            "gust_kph": 24.4,
            "uv": 1.0
          },
          {
            "time_epoch": 1697544000,
            "time": "2023-10-17 20:00",
            "temp_c": 29.0,
            "temp_f": 84.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 9.8,
            "wind_kph": 15.8,
            "wind_degree": 143,
            "wind_dir": "SE",
            "pressure_mb": 1010.0,
            "pressure_in": 29.82,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 72,
            "cloud": 18,
            "feelslike_c": 33.0,
            "feelslike_f": 91.5,
            "windchill_c": 29.0,
            "windchill_f": 84.1,
            "heatindex_c": 33.0,
            "heatindex_f": 91.5,
            "dewpoint_c": 23.4,
            "dewpoint_f": 74.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 14.0,
            "gust_kph": 22.6,
            "uv": 1.0
          },
          {
            "time_epoch": 1697547600,
            "time": "2023-10-17 21:00",
            "temp_c": 28.9,
            "temp_f": 84.0,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 128,
            "wind_dir": "SE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.84,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 72,
            "cloud": 21,
            "feelslike_c": 32.9,
            "feelslike_f": 91.3,
            "windchill_c": 28.9,
            "windchill_f": 84.0,
            "heatindex_c": 32.9,
            "heatindex_f": 91.3,
            "dewpoint_c": 23.3,
            "dewpoint_f": 74.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.8,
            "gust_kph": 22.2,
            "uv": 1.0
          },
          {
            "time_epoch": 1697551200,
            "time": "2023-10-17 22:00",
            "temp_c": 28.8,
            "temp_f": 83.9,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 10.3,
            "wind_kph": 16.6,
            "wind_degree": 116,
            "wind_dir": "ESE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.86,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 73,
            "cloud": 34,
            "feelslike_c": 32.9,
            "feelslike_f": 91.2,
            "windchill_c": 28.8,
            "windchill_f": 83.9,
            "heatindex_c": 32.9,
            "heatindex_f": 91.2,
            "dewpoint_c": 23.4,
            "dewpoint_f": 74.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 14.8,
            "gust_kph": 23.9,
            "uv": 1.0
          },
          {
            "time_epoch": 1697554800,
            "time": "2023-10-17 23:00",
            "temp_c": 28.7,
            "temp_f": 83.6,
            "is_day": 0,
            "condition": {
              "text": "Thundery outbreaks possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/200.png",
              "code": 1087
            },
            "wind_mph": 10.7,
            "wind_kph": 17.3,
            "wind_degree": 107,
            "wind_dir": "ESE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.86,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 74,
            "cloud": 49,
            "feelslike_c": 32.8,
            "feelslike_f": 91.1,
            "windchill_c": 28.7,
            "windchill_f": 83.6,
            "heatindex_c": 32.8,
            "heatindex_f": 91.1,
            "dewpoint_c": 23.6,
            "dewpoint_f": 74.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 15.4,
            "gust_kph": 24.8,
            "uv": 1.0
          }
        ]
      },
      {
        "date": "2023-10-18",
        "date_epoch": 1697587200,
        "day": {
          "maxtemp_c": 28.9,
          "maxtemp_f": 84.0,
          "mintemp_c": 27.5,
          "mintemp_f": 81.5,
          "avgtemp_c": 28.3,
          "avgtemp_f": 82.9,
          "maxwind_mph": 11.0,
          "maxwind_kph": 17.6,
          "totalprecip_mm": 15.23,
          "totalprecip_in": 0.6,
          "totalsnow_cm": 0.0,
          "avgvis_km": 9.8,
          "avgvis_miles": 6.0,
          "avghumidity": 74.0,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 88,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Moderate rain",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
            "code": 1189
          },
          "uv": 6.0
        },
        "astro": {
          "sunrise": "06:47 AM",
          "sunset": "06:52 PM",
          "moonrise": "09:24 AM",
          "moonset": "09:45 PM",
          "moon_phase": "Waxing Crescent",
          "moon_illumination": "11",
          "is_moon_up": 0,
          "is_sun_up": 1
        },
        "hour": [
          {
            "time_epoch": 1697558400,
            "time": "2023-10-18 00:00",
            "temp_c": 28.6,
            "temp_f": 83.5,
            "is_day": 0,
            "condition": {
              "text": "Thundery outbreaks possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/200.png",
              "code": 1087
            },
            "wind_mph": 10.5,
            "wind_kph": 16.9,
            "wind_degree": 110,
            "wind_dir": "ESE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.85,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 75,
            "cloud": 53,
            "feelslike_c": 32.8,
            "feelslike_f": 91.0,
            "windchill_c": 28.6,
            "windchill_f": 83.5,
            "heatindex_c": 32.8,
            "heatindex_f": 91.0,
            "dewpoint_c": 23.7,
            "dewpoint_f": 74.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 15.0,
            "gust_kph": 24.2,
            "uv": 1.0
          },
          {
            "time_epoch": 1697562000,
            "time": "2023-10-18 01:00",
            "temp_c": 28.5,
            "temp_f": 83.4,
            "is_day": 0,
            "condition": {
              "text": "Thundery outbreaks possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/200.png",
              "code": 1087
            },
            "wind_mph": 11.0,
            "wind_kph": 17.6,
            "wind_degree": 116,
            "wind_dir": "ESE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.84,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 75,
            "cloud": 65,
            "feelslike_c": 32.7,
            "feelslike_f": 90.9,
            "windchill_c": 28.5,
            "windchill_f": 83.4,
            "heatindex_c": 32.7,
            "heatindex_f": 90.9,
            "dewpoint_c": 23.7,
            "dewpoint_f": 74.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 15.5,
            "gust_kph": 24.9,
            "uv": 1.0
          },
          {
            "time_epoch": 1697565600,
            "time": "2023-10-18 02:00",
            "temp_c": 28.5,
            "temp_f": 83.2,
            "is_day": 0,
            "condition": {
              "text": "Thundery outbreaks possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/200.png",
              "code": 1087
            },
            "wind_mph": 10.7,
            "wind_kph": 17.3,
            "wind_degree": 122,
            "wind_dir": "ESE",
            "pressure_mb": 1010.0,
            "pressure_in": 29.82,
            "precip_mm": 0.04,
            "precip_in": 0.0,
            "humidity": 75,
            "cloud": 60,
            "feelslike_c": 32.5,
            "feelslike_f": 90.6,
            "windchill_c": 28.5,
            "windchill_f": 83.2,
            "heatindex_c": 32.5,
            "heatindex_f": 90.6,
            "dewpoint_c": 23.7,
            "dewpoint_f": 74.6,
            "will_it_rain": 1,
            "chance_of_rain": 78,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 15.2,
            "gust_kph": 24.4,
            "uv": 1.0
          },
          {
            "time_epoch": 1697569200,
            "time": "2023-10-18 03:00",
            "temp_c": 28.4,
            "temp_f": 83.1,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 125,
            "wind_dir": "SE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.81,
            "precip_mm": 0.14,
            "precip_in": 0.01,
            "humidity": 75,
            "cloud": 70,
            "feelslike_c": 32.3,
            "feelslike_f": 90.2,
            "windchill_c": 28.4,
            "windchill_f": 83.1,
            "heatindex_c": 32.3,
            "heatindex_f": 90.2,
            "dewpoint_c": 23.5,
            "dewpoint_f": 74.4,
            "will_it_rain": 0,
            "chance_of_rain": 66,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.7,
            "gust_kph": 22.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1697572800,
            "time": "2023-10-18 04:00",
            "temp_c": 28.3,
            "temp_f": 82.9,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 8.9,
            "wind_kph": 14.4,
            "wind_degree": 119,
            "wind_dir": "ESE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.8,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 75,
            "cloud": 61,
            "feelslike_c": 32.2,
            "feelslike_f": 89.9,
            "windchill_c": 28.3,
            "windchill_f": 82.9,
            "heatindex_c": 32.2,
            "heatindex_f": 89.9,
            "dewpoint_c": 23.5,
            "dewpoint_f": 74.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 12.8,
            "gust_kph": 20.5,
            "uv": 1.0
          },
          {
            "time_epoch": 1697576400,
            "time": "2023-10-18 05:00",
            "temp_c": 28.1,
            "temp_f": 82.5,
            "is_day": 0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 8.9,
            "wind_kph": 14.4,
            "wind_degree": 112,
            "wind_dir": "ESE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.81,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 76,
            "cloud": 86,
            "feelslike_c": 31.8,
            "feelslike_f": 89.3,
            "windchill_c": 28.1,
            "windchill_f": 82.5,
            "heatindex_c": 31.8,
            "heatindex_f": 89.3,
            "dewpoint_c": 23.4,
            "dewpoint_f": 74.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.0,
            "gust_kph": 20.9,
            "uv": 1.0
          },
          {
            "time_epoch": 1697580000,
            "time": "2023-10-18 06:00",
            "temp_c": 28.1,
            "temp_f": 82.6,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 112,
            "wind_dir": "ESE",
            "pressure_mb": 1010.0,
            "pressure_in": 29.82,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 76,
            "cloud": 100,
            "feelslike_c": 31.9,
            "feelslike_f": 89.4,
            "windchill_c": 28.1,
            "windchill_f": 82.6,
            "heatindex_c": 31.9,
            "heatindex_f": 89.4,
            "dewpoint_c": 23.5,
            "dewpoint_f": 74.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 12.1,
            "gust_kph": 19.5,
            "uv": 1.0
          },
          {
            "time_epoch": 1697583600,
            "time": "2023-10-18 07:00",
            "temp_c": 28.1,
            "temp_f": 82.5,
            "is_day": 1,
            "condition": {
              "text": "Patchy light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/293.png",
              "code": 1180
            },
            "wind_mph": 7.4,
            "wind_kph": 11.9,
            "wind_degree": 116,
            "wind_dir": "ESE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.84,
            "precip_mm": 1.07,
            "precip_in": 0.04,
            "humidity": 76,
            "cloud": 67,
            "feelslike_c": 31.9,
            "feelslike_f": 89.4,
            "windchill_c": 28.1,
            "windchill_f": 82.5,
            "heatindex_c": 31.9,
            "heatindex_f": 89.4,
            "dewpoint_c": 23.5,
            "dewpoint_f": 74.2,
            "will_it_rain": 1,
            "chance_of_rain": 88,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 10.5,
            "gust_kph": 16.9,
            "uv": 6.0
          },
          {
            "time_epoch": 1697587200,
            "time": "2023-10-18 08:00",
            "temp_c": 27.9,
            "temp_f": 82.2,
            "is_day": 1,
            "condition": {
              "text": "Patchy light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/293.png",
              "code": 1180
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 127,
            "wind_dir": "SE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.86,
            "precip_mm": 1.85,
            "precip_in": 0.07,
            "humidity": 77,
            "cloud": 88,
            "feelslike_c": 31.6,
            "feelslike_f": 88.9,
            "windchill_c": 27.9,
            "windchill_f": 82.2,
            "heatindex_c": 31.6,
            "heatindex_f": 88.9,
            "dewpoint_c": 23.5,
            "dewpoint_f": 74.3,
            "will_it_rain": 1,
            "chance_of_rain": 88,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 9.9,
            "gust_kph": 15.9,
            "uv": 6.0
          },
          {
            "time_epoch": 1697590800,
            "time": "2023-10-18 09:00",
            "temp_c": 28.0,
            "temp_f": 82.5,
            "is_day": 1,
            "condition": {
              "text": "Light rain shower",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
              "code": 1240
            },
            "wind_mph": 7.2,
            "wind_kph": 11.5,
            "wind_degree": 136,
            "wind_dir": "SE",
            "pressure_mb": 1012.0,
            "pressure_in": 29.88,
            "precip_mm": 1.2,
            "precip_in": 0.05,
            "humidity": 76,
            "cloud": 79,
            "feelslike_c": 31.9,
            "feelslike_f": 89.4,
            "windchill_c": 28.1,
            "windchill_f": 82.5,
            "heatindex_c": 31.9,
            "heatindex_f": 89.4,
            "dewpoint_c": 23.5,
            "dewpoint_f": 74.3,
            "will_it_rain": 1,
            "chance_of_rain": 78,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 10.4,
            "gust_kph": 16.7,
            "uv": 6.0
          },
          {
            "time_epoch": 1697594400,
            "time": "2023-10-18 10:00",
            "temp_c": 28.7,
            "temp_f": 83.7,
            "is_day": 1,
            "condition": {
              "text": "Light rain shower",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
              "code": 1240
            },
            "wind_mph": 8.3,
            "wind_kph": 13.3,
            "wind_degree": 141,
            "wind_dir": "SE",
            "pressure_mb": 1012.0,
            "pressure_in": 29.89,
            "precip_mm": 1.47,
            "precip_in": 0.06,
            "humidity": 72,
            "cloud": 70,
            "feelslike_c": 32.6,
            "feelslike_f": 90.7,
            "windchill_c": 28.7,
            "windchill_f": 83.7,
            "heatindex_c": 32.6,
            "heatindex_f": 90.7,
            "dewpoint_c": 23.3,
            "dewpoint_f": 73.9,
            "will_it_rain": 1,
            "chance_of_rain": 87,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 12.7,
            "gust_kph": 20.4,
            "uv": 6.0
          },
          {
            "time_epoch": 1697598000,
            "time": "2023-10-18 11:00",
            "temp_c": 28.9,
            "temp_f": 84.0,
            "is_day": 1,
            "condition": {
              "text": "Light rain shower",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
              "code": 1240
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 155,
            "wind_dir": "SSE",
            "pressure_mb": 1012.0,
            "pressure_in": 29.9,
            "precip_mm": 1.46,
            "precip_in": 0.06,
            "humidity": 70,
            "cloud": 83,
            "feelslike_c": 32.7,
            "feelslike_f": 90.8,
            "windchill_c": 28.9,
            "windchill_f": 84.0,
            "heatindex_c": 32.7,
            "heatindex_f": 90.8,
            "dewpoint_c": 23.0,
            "dewpoint_f": 73.3,
            "will_it_rain": 1,
            "chance_of_rain": 81,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 14.7,
            "gust_kph": 23.7,
            "uv": 6.0
          },
          {
            "time_epoch": 1697601600,
            "time": "2023-10-18 12:00",
            "temp_c": 28.9,
            "temp_f": 84.0,
            "is_day": 1,
            "condition": {
              "text": "Light rain shower",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
              "code": 1240
            },
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 161,
            "wind_dir": "SSE",
            "pressure_mb": 1012.0,
            "pressure_in": 29.88,
            "precip_mm": 1.18,
            "precip_in": 0.05,
            "humidity": 70,
            "cloud": 76,
            "feelslike_c": 32.6,
            "feelslike_f": 90.6,
            "windchill_c": 28.9,
            "windchill_f": 84.0,
            "heatindex_c": 32.6,
            "heatindex_f": 90.6,
            "dewpoint_c": 22.9,
            "dewpoint_f": 73.2,
            "will_it_rain": 1,
            "chance_of_rain": 78,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 14.5,
            "gust_kph": 23.3,
            "uv": 6.0
          },
          {
            "time_epoch": 1697605200,
            "time": "2023-10-18 13:00",
            "temp_c": 28.8,
            "temp_f": 83.8,
            "is_day": 1,
            "condition": {
              "text": "Light rain shower",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
              "code": 1240
            },
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 175,
            "wind_dir": "S",
            "pressure_mb": 1011.0,
            "pressure_in": 29.86,
            "precip_mm": 0.72,
            "precip_in": 0.03,
            "humidity": 71,
            "cloud": 71,
            "feelslike_c": 32.5,
            "feelslike_f": 90.5,
            "windchill_c": 28.8,
            "windchill_f": 83.8,
            "heatindex_c": 32.5,
            "heatindex_f": 90.5,
            "dewpoint_c": 22.9,
            "dewpoint_f": 73.2,
            "will_it_rain": 1,
            "chance_of_rain": 86,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 15.1,
            "gust_kph": 24.2,
            "uv": 6.0
          },
          {
            "time_epoch": 1697608800,
            "time": "2023-10-18 14:00",
            "temp_c": 28.8,
            "temp_f": 83.8,
            "is_day": 1,
            "condition": {
              "text": "Light rain shower",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
              "code": 1240
            },
            "wind_mph": 7.4,
            "wind_kph": 11.9,
            "wind_degree": 180,
            "wind_dir": "S",
            "pressure_mb": 1010.0,
            "pressure_in": 29.83,
            "precip_mm": 0.89,
            "precip_in": 0.04,
            "humidity": 71,
            "cloud": 72,
            "feelslike_c": 32.4,
            "feelslike_f": 90.3,
            "windchill_c": 28.8,
            "windchill_f": 83.8,
            "heatindex_c": 32.4,
            "heatindex_f": 90.3,
            "dewpoint_c": 22.9,
            "dewpoint_f": 73.1,
            "will_it_rain": 1,
            "chance_of_rain": 80,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 14.7,
            "gust_kph": 23.6,
            "uv": 6.0
          },
          {
            "time_epoch": 1697612400,
            "time": "2023-10-18 15:00",
            "temp_c": 28.6,
            "temp_f": 83.4,
            "is_day": 1,
            "condition": {
              "text": "Light rain shower",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
              "code": 1240
            },
            "wind_mph": 7.6,
            "wind_kph": 12.2,
            "wind_degree": 172,
            "wind_dir": "S",
            "pressure_mb": 1010.0,
            "pressure_in": 29.81,
            "precip_mm": 1.17,
            "precip_in": 0.05,
            "humidity": 72,
            "cloud": 84,
            "feelslike_c": 32.2,
            "feelslike_f": 90.0,
            "windchill_c": 28.6,
            "windchill_f": 83.4,
            "heatindex_c": 32.2,
            "heatindex_f": 90.0,
            "dewpoint_c": 22.9,
            "dewpoint_f": 73.3,
            "will_it_rain": 1,
            "chance_of_rain": 76,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 10.2,
            "gust_kph": 16.3,
            "uv": 6.0
          },
          {
            "time_epoch": 1697616000,
            "time": "2023-10-18 16:00",
            "temp_c": 28.3,
            "temp_f": 82.9,
            "is_day": 1,
            "condition": {
              "text": "Light rain shower",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
              "code": 1240
            },
            "wind_mph": 7.6,
            "wind_kph": 12.2,
            "wind_degree": 161,
            "wind_dir": "SSE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.8,
            "precip_mm": 1.0,
            "precip_in": 0.04,
            "humidity": 73,
            "cloud": 73,
            "feelslike_c": 31.9,
            "feelslike_f": 89.3,
            "windchill_c": 28.3,
            "windchill_f": 82.9,
            "heatindex_c": 31.9,
            "heatindex_f": 89.3,
            "dewpoint_c": 23.0,
            "dewpoint_f": 73.4,
            "will_it_rain": 0,
            "chance_of_rain": 64,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 11.5,
            "gust_kph": 18.6,
            "uv": 6.0
          },
          {
            "time_epoch": 1697619600,
            "time": "2023-10-18 17:00",
            "temp_c": 28.4,
            "temp_f": 83.2,
            "is_day": 1,
            "condition": {
              "text": "Light rain shower",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
              "code": 1240
            },
            "wind_mph": 7.2,
            "wind_kph": 11.5,
            "wind_degree": 152,
            "wind_dir": "SSE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.8,
            "precip_mm": 0.19,
            "precip_in": 0.01,
            "humidity": 71,
            "cloud": 62,
            "feelslike_c": 31.9,
            "feelslike_f": 89.5,
            "windchill_c": 28.4,
            "windchill_f": 83.2,
            "heatindex_c": 31.9,
            "heatindex_f": 89.5,
            "dewpoint_c": 22.8,
            "dewpoint_f": 73.0,
            "will_it_rain": 0,
            "chance_of_rain": 67,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 11.6,
            "gust_kph": 18.6,
            "uv": 6.0
          },
          {
            "time_epoch": 1697623200,
            "time": "2023-10-18 18:00",
            "temp_c": 28.6,
            "temp_f": 83.5,
            "is_day": 1,
            "condition": {
              "text": "Light rain shower",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
              "code": 1240
            },
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 153,
            "wind_dir": "SSE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.81,
            "precip_mm": 0.49,
            "precip_in": 0.02,
            "humidity": 71,
            "cloud": 54,
            "feelslike_c": 32.2,
            "feelslike_f": 90.0,
            "windchill_c": 28.6,
            "windchill_f": 83.5,
            "heatindex_c": 32.2,
            "heatindex_f": 90.0,
            "dewpoint_c": 22.9,
            "dewpoint_f": 73.2,
            "will_it_rain": 1,
            "chance_of_rain": 75,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.0,
            "gust_kph": 20.9,
            "uv": 6.0
          },
          {
            "time_epoch": 1697626800,
            "time": "2023-10-18 19:00",
            "temp_c": 28.0,
            "temp_f": 82.4,
            "is_day": 0,
            "condition": {
              "text": "Light rain shower",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
              "code": 1240
            },
            "wind_mph": 8.9,
            "wind_kph": 14.4,
            "wind_degree": 154,
            "wind_dir": "SSE",
            "pressure_mb": 1010.0,
            "pressure_in": 29.83,
            "precip_mm": 0.95,
            "precip_in": 0.04,
            "humidity": 75,
            "cloud": 63,
            "feelslike_c": 31.5,
            "feelslike_f": 88.8,
            "windchill_c": 28.0,
            "windchill_f": 82.4,
            "heatindex_c": 31.5,
            "heatindex_f": 88.8,
            "dewpoint_c": 23.1,
            "dewpoint_f": 73.5,
            "will_it_rain": 0,
            "chance_of_rain": 57,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 15.8,
            "gust_kph": 25.4,
            "uv": 1.0
          },
          {
            "time_epoch": 1697630400,
            "time": "2023-10-18 20:00",
            "temp_c": 27.8,
            "temp_f": 82.0,
            "is_day": 0,
            "condition": {
              "text": "Light rain shower",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
              "code": 1240
            },
            "wind_mph": 8.9,
            "wind_kph": 14.4,
            "wind_degree": 150,
            "wind_dir": "SSE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.86,
            "precip_mm": 0.48,
            "precip_in": 0.02,
            "humidity": 76,
            "cloud": 89,
            "feelslike_c": 31.3,
            "feelslike_f": 88.3,
            "windchill_c": 27.8,
            "windchill_f": 82.0,
            "heatindex_c": 31.3,
            "heatindex_f": 88.3,
            "dewpoint_c": 23.2,
            "dewpoint_f": 73.7,
            "will_it_rain": 0,
            "chance_of_rain": 64,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 16.4,
            "gust_kph": 26.5,
            "uv": 1.0
          },
          {
            "time_epoch": 1697634000,
            "time": "2023-10-18 21:00",
            "temp_c": 27.6,
            "temp_f": 81.6,
            "is_day": 0,
            "condition": {
              "text": "Light rain shower",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
              "code": 1240
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 134,
            "wind_dir": "SE",
            "pressure_mb": 1012.0,
            "pressure_in": 29.88,
            "precip_mm": 0.8,
            "precip_in": 0.03,
            "humidity": 78,
            "cloud": 66,
            "feelslike_c": 31.1,
            "feelslike_f": 88.0,
            "windchill_c": 27.6,
            "windchill_f": 81.6,
            "heatindex_c": 31.1,
            "heatindex_f": 88.0,
            "dewpoint_c": 23.3,
            "dewpoint_f": 74.0,
            "will_it_rain": 0,
            "chance_of_rain": 58,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.6,
            "gust_kph": 21.9,
            "uv": 1.0
          },
          {
            "time_epoch": 1697637600,
            "time": "2023-10-18 22:00",
            "temp_c": 27.5,
            "temp_f": 81.6,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 9.8,
            "wind_kph": 15.8,
            "wind_degree": 127,
            "wind_dir": "SE",
            "pressure_mb": 1013.0,
            "pressure_in": 29.9,
            "precip_mm": 0.07,
            "precip_in": 0.0,
            "humidity": 78,
            "cloud": 73,
            "feelslike_c": 31.1,
            "feelslike_f": 87.9,
            "windchill_c": 27.6,
            "windchill_f": 81.6,
            "heatindex_c": 31.1,
            "heatindex_f": 87.9,
            "dewpoint_c": 23.3,
            "dewpoint_f": 74.0,
            "will_it_rain": 1,
            "chance_of_rain": 80,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 14.0,
            "gust_kph": 22.6,
            "uv": 1.0
          },
          {
            "time_epoch": 1697641200,
            "time": "2023-10-18 23:00",
            "temp_c": 27.5,
            "temp_f": 81.5,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 132,
            "wind_dir": "SE",
            "pressure_mb": 1012.0,
            "pressure_in": 29.89,
            "precip_mm": 0.06,
            "precip_in": 0.0,
            "humidity": 78,
            "cloud": 100,
            "feelslike_c": 31.1,
            "feelslike_f": 87.9,
            "windchill_c": 27.5,
            "windchill_f": 81.6,
            "heatindex_c": 31.1,
            "heatindex_f": 87.9,
            "dewpoint_c": 23.4,
            "dewpoint_f": 74.1,
            "will_it_rain": 1,
            "chance_of_rain": 86,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.4,
            "gust_kph": 21.6,
            "uv": 1.0
          }
        ]
      }
    ]
  }
};
